// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfrulnpmddrcflhayghf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcnVsbnBtZGRyY2ZsaGF5Z2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODU3ODMsImV4cCI6MjA2Mjc2MTc4M30.6QA-o9gsBr_NKZkE8I35i1tXmMBqUq56-H7B60G4F6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);